insert into EVENT_REGISTRY values('E1','Prospect Completed');
insert into EVENT_REGISTRY values('E2','Entity Profile Created');
insert into EVENT_REGISTRY values('E3','Hierarchy Captured');
insert into EVENT_REGISTRY values('E4','Entity Validated');
insert into EVENT_REGISTRY values('E5','KYC Profile Created');
insert into EVENT_REGISTRY values('E6','Unwrapping Completed');
insert into EVENT_REGISTRY values('E7','Pre-Tax Completed');
insert into EVENT_REGISTRY values('E8','Risk Flag Identified');
insert into EVENT_REGISTRY values('E9','ID&V Completed');
insert into EVENT_REGISTRY values('E10','Screening Completed');
insert into EVENT_REGISTRY values('E11','KYC Approved');
insert into EVENT_REGISTRY values('E12','FATCA Approved');
insert into EVENT_REGISTRY values('E13','CRS Completed');
insert into EVENT_REGISTRY values('E14','KYC Overdue');
